# Site settings
title: 欧易OKX中文官方教程
email: dh7440234@gmail.com 
description: > # this means to ignore newlines until "baseurl:"
  欧易OKX、OKEX官方中文教程，提供最新最全的使用指南，详细讲解注册、交易、充提币等操作流程，帮助用户快速上手欧易平台，了解各项功能与操作技巧，轻松玩转数字资产交易。
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://okxzh.github.io/" # the base hostname & protocol for your site
twitter_username: idanhua
github_username:  tggsearch

# Build settings
markdown: kramdown
